name: solandra
description: Make drawing with Flutter concise, powerful and easy. 2D creative code/algorithmic art framework with helpers for creating shapes, iteration, (pseudo)randomness and more.
version: 0.0.4
homepage: https://solandra.netlify.app/
repository: https://github.com/jamesporter/solandra-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
